[build-system]
# These are the requirements for building the package
requires = ["setuptools>=75.1.0", "wheel>=0.44.0"]
build-backend = "setuptools.build_meta"

[project]
# Basic project metadata
name = "GenerativeNetworkModels"
version = "0.1"
description = """
This package provides computationally efficient tools for implementing Weighted
Generative Models (WGMs) in network neuroscience. Unlike Binary Generative Models (BGMs),
WGMs capture the strength of connections between network nodes. Optimized in Python,
these tools offer an intuitive, graph-theoretic approach to modeling connectomes,
improving efficiency over existing implementations such as the Brain Connectivity
Toolbox and recent WGM research code."""
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Edward Young", email = "ey245@cam.ac.uk"},
    {name = "William Mills", email = "william.mills@mrc-cbu.cam.ac.uk"},
    {name = "Francesco Poli", email = "francesco.poli@mrc-cbu.cam.ac.uk"}
]

# Dependencies
dependencies = [
    "jaxtyping==0.2.36",
    "setuptools==75.1.0",
    "six==1.16.0",
    "sympy==1.13.3",
    "tqdm==4.66.5",
    "typeguard==2.13.3",
    "typing-extensions==4.12.2",
    "urllib3==2.3.0",
    "wheel==0.44.0",
    "zipp==3.21.0",
    "wandb", 
]

keywords = [
    "network-science",
    "neuroscience",
    "generative-models",
    "weighted-networks",
    "brain-connectivity",
    "network-analysis",
    "graph-theory",
    "connectomics"
]

classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Framework :: Jupyter",
    "License :: OSI Approved :: MIT License"  # Added based on MIT license
]

[project.urls]
# Project URLs
Homepage = "https://github.com/EdwardJamesYoung/GenerativeNetworkModels"
Documentation = "https://generative-network-models-toolbox.readthedocs.io/en/latest/"
Repository = "https://github.com/EdwardJamesYoung/GenerativeNetworkModels.git"
"Bug Tracker" = "https://github.com/EdwardJamesYoung/GenerativeNetworkModels/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["gnm*"]

[tool.setuptools.package-data]
# Include any package data files
"*" = ["*.txt", "*.rst", "*.md"]