from setuptools import setup

setup(
    name='GenerativeNetworkTools',
    version='0.1',    
    description="""
    This package provides computationally efficient tools for implementing Weighted 
    Generative Models (WGMs) in network neuroscience. Unlike Binary Generative Models (BGMs), 
    WGMs capture the strength of connections between network nodes. Optimized in Python, 
    these tools offer an intuitive, graph-theoretic approach to modeling connectomes, 
    improving efficiency over existing implementations such as the Brain Connectivity 
    Toolbox and recent WGM research code.""",

    url='https://github.com/EdwardJamesYoung/GenerativeNetworkModels',
    author='Edward Young, Francesco Poli, William Mills',
    author_email='ey245@cam.ac.uk, francesco.poli@mrc-cbu.cam.ac.uk, william.mills@mrc-cbu.cam.ac.uk',
    license='',
    packages=['GenerativeNetworkModels'],
    install_requires=[
        "anyio==4.6.2.post1",
        "argon2-cffi==23.1.0",
        "argon2-cffi-bindings==21.2.0",
        "arrow==1.3.0",
        "async-lru==2.0.4",
        "attrs==24.2.0",
        "babel==2.16.0",
        "beautifulsoup4==4.12.3",
        "bleach==6.2.0",
        "cffi==1.17.1",
        "contourpy==1.3.0",
        "cycler==0.12.1",
        "defusedxml==0.7.1",
        "fastjsonschema==2.20.0",
        "fonttools==4.54.1",
        "fqdn==1.5.1",
        "h11==0.14.0",
        "httpcore==1.0.6",
        "httpx==0.27.2",
        "ipywidgets==8.1.5",
        "isoduration==20.11.0",
        "jax==0.4.35",
        "jaxlib==0.4.34",
        "jaxtyping==0.2.34",
        "json5==0.9.25",
        "jsonpointer==3.0.0",
        "jsonschema==4.23.0",
        "jupyter==1.1.1",
        "jupyter-console==6.6.3",
        "jupyter-events==0.10.0",
        "jupyter-server==2.14.2",
        "jupyterlab==4.2.5",
        "kiwisolver==1.4.7",
        "matplotlib==3.9.2",
        "mistune==3.0.2",
        "ml_dtypes==0.5.0",
        "nbclient==0.10.0",
        "nbconvert==7.16.4",
        "nbformat==5.10.4",
        "networkx",
        "notebook==7.2.2",
        "numpy==2.1.1",
        "opt_einsum==3.4.0",
        "overrides==7.7.0",
        "packaging",
        "pandas",
        "Pillow",
        "prometheus_client==0.21.0",
        "pycparser==2.22",
        "Pygments",
        "pyparsing==3.2.0",
        "python-dateutil",
        "PyYAML",
        "requests",
        "scipy==1.14.1",
        "Send2Trash",
        "six",
        "sniffio",
        "soupsieve",
        "sympy",
        "terminado",
        "tinycss2",
        "torch==2.5.1",
        "torchaudio==2.5.1",
        "torchvision==0.20.1",
        "tornado",
        "tqdm",
        "traitlets",
        "triton==3.1.0",
        "typeguard==2.13.3",
        "typing_extensions",
        "urllib3",
        "webcolors",
        "websocket-client",
        "wheel",
        "widgetsnbextension",
    ],

    python_requires=">=3.9",

    classifiers=[
        "Development Status :: 1 - Planning",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Developers",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Mathematics",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Framework :: Jupyter",

        # need to add license
    ]
)